name: Deploy to one.com
on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        ftp-server: ftp://ftp.one.com
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ../../.next
